#!/bin/sh
#
#	program:	speed-run
#
#	input:		./speed-run task-list-to-change
#
#	location:	run from anyhere in the repo.
#			It operates on the right folder
#			but does not change working dir in terminal.
#
#	usage:		Use on one task list at a time.
#			Designed as a tool to modularize
#			a task lists from 4th to 5th 
#			task list editions.
#			
#			This script divides the task-list modules to 
#			subfiles and returns a summary report.
#
#	argument:	name of folder for task list to change.
#	
#	Do Not Use:	On Section A, fifth ed (I did that by hand).
#
# (Design steps commented below.)
#
#	argument from command line
echo Which task list folder to you want to modularize?
read current			# current task list item

#	alternate version: just take arg from program call.
#current="$1"			# current task list item

#	navigate to correct directory.
cd ~/Documents/GitHub/trainaba-v1-ed2/tex/chapters/fifth-ed/tl-modules/$current
echo Switching directories. Now in:
pwd

#	reminder
echo Remember to stage $current/body.tex

#       ranger program
#	sed scripts to redirect body.tex to subfiles.
echo This program copies a range of lines to a tex file.
echo Which section do you want to make?
select section in "nfo" "xmplz" "ssmt" "lit" "lssnz" "done"; do
        case $section in
                nfo   )  ./ranger nfo;;
                xmplz )  ./ranger xmplz;;
                ssmt  )  ./ranger ssmt;;
                lit   )  ./ranger lit;;
                lssnz )  ./ranger lssnz;;
                done  )   exit;;
	    esac
done

#	overwrite body.tex
echo "Overwrite body file AFTER the subfiles. Ready to overwrite?"
select yn in "Yes" "No"; do
    case $yn in

        Yes )	cat ../fiveaOne/body.tex > $current/body.tex; 
		sed -i -- "s/fiveaOne/$current/g" body.tex;
		break;;

        No  )	echo "Exiting without overwriting $current/body.tex...";
		exit;;
    esac
done

echo "Number of lines in $current/body.tex:"
cat body.tex | wc -l

echo Done. Use gitcom if everything looks good.