#!/bin/sh
#
#	program:	list-from-task-list
#
#	related:	list-from-task-list
#			stage-dirs
#			mk-dirs
#			
#	usage:		Use every five years, when BACB updates task list.
#
#			Unix script. Use with task list variables.
#			
#			Purpose of this script is to generate a list of each
#			task list item on its own line.
#			
#			Then it's easy to count them and make dirs.
#			Each dir holds the data for a task list item.
#			The module gets called from a main file.
#			
#			Goal is to keep TrainABA Documentation clean.
#
#	author:		Ben Theisen, 2020 Nov 6. CC 4.0 - BY-NC-ND
echo "Extracting list of task lists now..."
grep -F '\newcommand' ../../style/tlsix.sty | grep -F '\six' | cut -d'{' -f2 | cut -d'}' -f1 | cut -d'\' -f2 | grep -v 'sixsec' > ../../tex/chapters/new-dirs-list.txt
echo "File complete."
echo "Location: ../../tex/chapters/new-dirs-list.txt"
echo "Number of items in list is: "
cat ../../tex/chapters/new-dirs-list.txt | wc -l

