#!/bin/sh
#
#	program:	make-subfiles
#
#	input:		./make-subfiles task-list-to-change
#
#	location:	run from anyhere in the repo.
#			It operates on the right folder
#			but does not change working dir in terminal.
#
#	usage:		Use on one task list at a time.
#			Calls a subroutine, ./ranger, to copy range areas.
#	
#	Purpose:	Designed as a tool to modularize
#			a task lists from 4th to 5th 
#			task list editions.
#			
#			This script divides the task-list modules to 
#			subfiles and returns a summary report.
#
#	argument:	name of folder for task list to change.
#	
#	Do Not Use:	On Section A, fifth ed (I did that by hand).
#
# (Design steps commented below.)
#
#	argument from command line
current="$1"			# current task list item
cyan='\033[0;36m'
red='\033[1;31m'
green='\033[1;32m'
bldcyan='\033[1;96m'		
yellow='\033[1;33m'
blue='\033[1;34m'
ltpurple='\033[0;35m'
nc='\033[0m' # No Color

welcome="${cyan}Welcome to Subfile Menu${nc}"
menu="${red}1=nfo${nc}, ${green}2=xmplz${nc}, ${bldcyan}3=ssmt${nc}, ${yellow}4=lit${nc}, ${blue}5=lssnz${nc}, ${ltpurple}6=done"
#	navigate to correct directory.
cd ~/Documents/GitHub/trainaba-v1-ed2/tex/chapters/fifth-ed/tl-modules/$current

#	Present subfile menu.
echo "You are about to make edits on:"
pwd
echo "The next steps will copy a range of lines to subfiles."
#echo "${cyan}Which range do you want to target?${nc}"
echo $welcome
echo $menu
#	Make a temporary copy of subroutines.
cp ~/Documents/GitHub/trainaba-v1-ed2/notes/scripts/ranger temp-ranger
#cp ~/Documents/GitHub/trainaba-v1-ed2/notes/scripts/tagger temp-tagger
#cp ~/Documents/GitHub/trainaba-v1-ed2/notes/scripts/tag-extractor temp-tag-extractor

#	Clean up body.tex before opening.
#echo running tagger...
#./temp-tagger
#echo extracting tags...
#./temp-tag-extractor

#	Open body file so it's easier to read.
open -a TeXShop body.tex 

select section in "nfo" "xmplz" "ssmt" "lit" "lssnz" "done"; do
    case $section in
	nfo   )	 ./temp-ranger nfo;
		 echo $welcome;
		 echo $menu;;
	xmplz )  ./temp-ranger xmplz;
		 echo $welcome;
		 echo $menu;;
	ssmt  )  ./temp-ranger ssmt;
		 echo $welcome;
		 echo $menu;;
	lit   )  ./temp-ranger lit;
		 echo $welcome;
		 echo $menu;;
	lssnz )  ./temp-ranger lssnz;
		 echo $welcome;
		 echo $menu;;
	done  )  break;;
    esac
done

#	Clean up temp program.
rm temp-ranger
#rm temp-tagger
#rm temp-tag-extractor

echo "${red}Overwrite $current/body.tex? Cannot be undone.${nc}"
select yn in "Yes" "No"; do
    case $yn in
	Yes )	cat ../fiveaOne/body.tex > body.tex;
		sed -i -- "s/fiveaOne/$current/g" body.tex;
		rm body.tex--   # clean up temp file, not sure how created.
		break;;
        
	No  )	echo "Cancelling. Always smart to be safe...";
		break;;
    esac
done
 

#	Closing message.
echo "Number of lines in new ${yellow}body${nc}.tex file:"
echo "Expected: 8"
echo "Actual:"
cat body.tex | wc -l
echo "If is what you expected, run a git commit."
