#!/bin/sh
#
#	program:	ranger
#
#	input:		./ranger subfile-to-edit
#
#	location:	Subroutine to ./make-subfiles.
#
#	usage:		Use on one task list at a time.
#			Designed as a tool to modularize
#			a task lists from 4th to 5th 
#			task list editions.
#			
#			This script divides the task-list modules to 
#			subfiles and returns a summary report.
#
#	argument:	first arg is the subfile to edit (*.tex).
#
sub="$1"
echo Enter first and last lines to write to $sub.tex:
read beg end
 
#	Confirm input
echo Here are the ranges I\'ll copy.
echo "from body.tex lines $beg, $end to $sub.tex"

#	Show content to be copied. 
#echo Here is what\'s in that range:
#sed -n "${beg},${end}p" body.tex 

#echo "Do you wish to write range to $sub.tex?"
#select yn in "Yes" "No"; do
#    case $yn in
#	Yes ) sed -n "${beg},${end}p" body.tex >> $sub.tex; break;;
#        No ) echo "Cancelling. Always smart to be safe...";exit;;
#    esac
#done

while true; do
    read -p "Write range to $sub.tex?" yn
    case $yn in
        [Yy]* ) sed -n "${beg},${end}p" body.tex >> $sub.tex; 
		echo Done. Copied range to $sub.tex;
		break;;
        [Nn]* ) echo "Canceled. Always smart to be safe...";
		exit;;
        * ) echo "Yes or no.";;
    esac
done
