#!/bin/sh
#
# program: tagger
# 
# usage: tool to add tags before and after certain sections from 4th to 5th ed. 
# Not general purpose. 
# 
# Design Steps, using '|' as placeholder for '\n' until end:
# 
# Create Assessment tag.
find . -type f -name 'body.tex' -print0 | xargs -0 sed -i '' 's=\\subsection{Assessment=|<ssmt>|%\\subsection{Assessment=g' 

# Close Assessment tag and open Relevant Literature tag.
find . -type f -name 'body.tex' -print0 | xargs -0 sed -i '' 's=\\subsection{Relevant =|<\/ssmt>|%|<lit>|%\\subsection{Relevant =g'

# Close Relevant Literature tag.
find . -type f -name 'body.tex' -print0 | xargs -0 sed -i '' 's=\\subsection{Related =|<\/lit>|%\\subsection{Related =g'

# Fix newline characters after each tag.
cat body.tex  | tr '|' '\n'    > temp 
cat temp > body.tex
rm temp
